steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', '$LOCATION-docker.pkg.dev/$PROJECT_ID/arcognition/backend:$COMMIT_SHA', '.' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', '$LOCATION-docker.pkg.dev/$PROJECT_ID/arcognition/backend:$COMMIT_SHA' ]
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [ 'run', 'deploy', 'arcognition-api', '--image', '$LOCATION-docker.pkg.dev/$PROJECT_ID/arcognition/backend:$COMMIT_SHA', '--region', '$LOCATION', '--platform', 'managed', '--allow-unauthenticated' ]
images:
  - '$LOCATION-docker.pkg.dev/$PROJECT_ID/arcognition/backend:$COMMIT_SHA'
